local ADDON_NAME, ns = ...

BitForge.Events = {
    CORE_LOADED          = "BITFORGE_CORE_LOADED",
    PLAYER_READY         = "BITFORGE_PLAYER_READY",
    PLAYER_LEAVING       = "BITFORGE_PLAYER_LEAVING",
    MODULE_ENABLED       = "BITFORGE_MODULE_ENABLED",   -- arg: addonName
    MODULE_DISABLED      = "BITFORGE_MODULE_DISABLED",  -- arg: addonName
    BANK_OPENED          = "BITFORGE_BANK_OPENED",
    BANK_CLOSED          = "BITFORGE_BANK_CLOSED",
    SKILL_LINES_CHANGED  = "BITFORGE_SKILL_LINES_CHANGED",
}
