-- Release notes shown in the in-client What's New window.
--
-- GENERATED by Scripts/build_release_notes.py from CHANGELOG.md. Do not edit
-- by hand: tests/python/test_release_notes.py re-runs the generator and
-- compares, so a hand edit fails the suite rather than surviving in it.
--
-- ENGLISH ONLY, DELIBERATELY. The window's chrome is localized; the document
-- inside it is not -- these strings carry no Locales/ entry and never will.
--
-- ONLY THE NEWEST 5 RELEASES ARE HERE. An older version's notes are
-- gone, not missing: CHANGELOG.md still has them, this table never will.
--
-- `lead` IS OPTIONAL. It is a bullet's bold prefix, where the source bullet
-- had one; 3 of the 73 items below have none, so a consumer
-- must not assume every item carries one.
--
-- `sep` IS THE SEPARATOR THE CHANGELOG WROTE between a lead and the rest of
-- the bullet -- an em dash or a colon, recorded rather than dropped. ABSENT
-- MEANS THE SOURCE WROTE NEITHER, not that one went missing: 64 of the
-- 70 leads below have no `sep`, and supplying one for those strands a
-- predicate with nothing in front of it ("BatchSell -- now asks ...").
--
-- 5 releases, 73 items, v12.1.0.7 down to v12.1.0.3.

---@class BitForge.Core
local ns = select(2, ...)

---@type BitForge.Core.Enum
local enum = ns.enum

enum.RELEASE_NOTES = {
    {
        version = "v12.1.0.7",
        date = "2026-08-27",
        sections = {
            {
                heading = "Added",
                items = {
                    { lead = "Tell us when BitForge gets an item wrong.", text = "BatchSell's sell list and Openables' button now offer to report the item you are looking at: a window opens with everything BitForge judged it by, already selected, and the address to paste it into. It needs nothing turned on first. The window shows you the whole report rather than hiding it behind a button, and says plainly what it discloses — for BatchSell that is the item's link, which states your character's level and specialization, and whatever you have equipped in the slot it would fill; for Openables it is the item, how it was classified, and which professions the character knows. Neither names your character, realm, guild or faction. Reach it from the menu on a row in the sell list, or with Shift + Alt + right-click on Openables' button." },
                    { lead = "BitForge tells you what changed after it updates.", text = "The first time you log in on a new version, a window lists everything new since the version you last saw, and does not come back until the next update. /bitforge core whatsnew opens it again." },
                    { lead = "RepRank:", text = "factions are grouped by expansion, under the same headings the game's own reputation pane uses, indented beneath the Warband and Characters sections. Sorting by rank now orders factions within their expansion rather than across the whole list. A faction recorded before this update sits under \"Other\" until the character holding it next logs in." },
                    { lead = "Openables:", text = "an item that starts a quest is now marked with a bold gold exclamation mark in the button's top-left corner, so you can tell a quest you can pick up from an ordinary item at a glance." },
                    { lead = "EUI", text = ", a new module: precise, numeric control over EllesmereUI's frame positions. Installing it changes nothing — it records where your frames already are and moves none of them until you edit something. It also offers attachments EllesmereUI cannot express, resolving those itself. EllesmereUI is required." },
                    { lead = "The suite's slash commands are now owned by BitForge itself.", text = "/bitforge <module> opens or acts on a module, in place of the separate command each module used to install for itself. /bitforge on its own prints the modules you have installed, so the list cannot go stale the way a written-down one does. A module name shortens to any unambiguous prefix, making /bitforge b and /bitforge batchsell the same command, and asking a module for something it does not offer says so instead of doing nothing." },
                    { lead = "A close button that matches the window it sits on.", text = "Openables, RepRank, UPS and both of TaskTome's windows now draw their X in BitForge's own colours instead of wearing Blizzard's red one, and it lights up under the pointer. EUI's editor deliberately keeps EllesmereUI's, since that window is a guest in EllesmereUI's layout and should look like the rest of it." },
                    { lead = "BatchSell can show you why.", text = "A new Rules window lists every criterion it judges an item by, in the order it checks them, with a plain-English explanation of each — from the Rules button at the vendor, or from BatchSell's settings. Every criterion that has anything to set is now set from the window itself, each control explaining what it does when you point at it: whether poor quality items sell, how gear is compared with what you are wearing, and the rules for crafting reagents, uncollected appearances, gems, enhancements, recipes, mounts and pets, and housing. Which of your professions spares a trade good is set here too, from a list you tick. Consumables get a row each, with their options behind it. A setting that only matters while another is on greys out until it is, and changing anything at a vendor updates the sell list straight away. The pane scrolls when a criterion has more to say than fits. The manifest also tells you what to do when something you expected to sell is not listed: hover it in your bags and the tooltip names the rule that kept it." },
                },
            },
            {
                heading = "Changed",
                items = {
                    { lead = "BatchSell:", text = "the menu on an item in the sell list now shows what that item is already set to. It has a Character section and a Warband section, each offering Blacklisted, Whitelisted and None, so a warband entry being overridden on this character is finally visible — the old menu offered four ways to set a status and no way to see which was set. Clearing one scope leaves the other standing: Clear Character Override is now Character → None, and Remove From List is None in both." },
                    { lead = "BatchSell judges recipes straight away now.", text = "A recipe used to be left alone until you had opened that profession's window at least once; it is judged from the item itself from now on, so \"keep what I can still learn\" and \"keep what is still tradeable\" apply on your first visit to a vendor. A recipe that belongs to no one profession — a generic pattern or manual — is still left alone, since there is nothing to judge it against." },
                    { lead = "The crafting-reagent catalogue is now read from the game itself rather than from a website.", text = "It covers 2,833 reagents across the ten professions that have recipes, up from 2,200, and for the first time it carries the optional reagents a recipe accepts and every quality tier of a reagent instead of only the first. Fewer materials will be offered for sale because BitForge had never heard of them. It also asks nothing of you: opening each of your profession windows used to be how the list filled itself in, and there is no longer anything to fill in — what ships is the whole of it, and reagents a later patch adds wait for the next update rather than for you." },
                    { lead = "BatchSell", text = "now decides by the kind of item. Every kind has its own rule — consumables, gems, trade goods, recipes, companion pets and mounts, housing decor, gear — instead of everything being sorted into equipment, materials or other and the last two sharing one keep-or-sell setting. A kind with no rule of its own is never examined, so quest items, keys, glyphs and anything else BatchSell does not understand stay in your bags no matter how the rest is set. Crafting materials and consumables are affected most: they used to answer to a single expansion-age setting, and now each kind answers for itself." },
                    { lead = "BatchSell", text = "never sells on something it could not read. If the game has not finished loading an item's details, or has not told BatchSell what you have equipped, or what your character's class is, the item is kept rather than judged on a blank. This mattered most right after logging in or reloading at a vendor. The same goes for the reagent list: a trade good, consumable or gem that BatchSell's list has no entry for is kept rather than sold, since not knowing whether a profession wants it is not the same as knowing none does. Expect fewer trade goods to sell than before, especially just after a patch adds new ones." },
                    { lead = "BatchSell", text = "settings are now shared across your warband instead of being set per character, and your existing settings are reset once when you first log in after this update. They could not be carried over: there was no way to tell which character's settings should become everyone's. The batch limit stays on, so a first sell after the update is still capped." },
                    { lead = "BatchSell:", text = "two defaults changed. Selling poor quality items is now off, since another addon usually handles it — turn it back on if nothing else does. Keeping gear worth disenchanting is now on." },
                    { lead = "BatchSell spares unbound Bind on Equip gear by default.", text = "A new Spare Bind on Equip Gear dropdown sits beside the Bind on Account one and ships on Current Expansion, so a current-expansion piece you have never worn is kept for an alt or the auction house even when it loses the comparison. Expect some gear you used to see vendored to stay in your bags. Set it to All to keep older Bind on Equip gear too, or None to have it judged like anything else." },
                    { lead = "BatchSell:", text = "every per-kind rule is now yours to set, in the Rules window. Consumables are the finest-grained of them: potions, elixirs, flasks and phials, food and drink, bandages, vantus runes and the rest each get their own answer, and the four that can be levelled through offer to keep last expansion's as well. The defaults are unchanged, so nothing starts selling that was not selling before." },
                    { lead = "BatchSell's settings panel no longer holds any rule.", text = "Sell Junk, Keep Reagents Your Professions Use and the seven gear settings have moved into the Rules window, where the other forty-five already were. What is left in the Blizzard settings panel is the batch limit, the four list resets, and the button that opens the window. If you knew where those nine were, they are one button away now — and there is no longer a second place a rule can be set from." },
                    { lead = "BatchSell", text = "ships those new rules on defaults you can change: a housing dye you could still trade or sell is kept and one bound to you is sold; housing decor and battle pets are kept; and a mount is kept unless it is bound to you and you have already collected it." },
                    { lead = "BatchSell", text = "explains a sold relic properly. The verdict read \"Relics are sold\", which said nothing about why and used the same word as the artifact relics it keeps. It now says nothing can equip a relic any more — idols, librams, totems and sigils belong to a slot the game removed. All eleven languages; nothing behaves differently." },
                },
            },
            {
                heading = "Removed",
                items = {
                    { text = "/bfodump, /bfsdump and /bfsde are gone." },
                    { lead = "BatchSell:", text = "the Sell Equipment checkbox is gone, and so are the Crafting Materials and Consumables & Other sections along with their keep-or-sell dropdowns — every kind of item now answers for itself instead. If you used Sell Equipment to keep all your gear, turn off both Compare Quality and Compare Item Level: nothing your class can equip is vendored then. Gear your class cannot use is still judged, and what keeps it is the Spare Bind on Account, Spare Bind on Equip and Keep Disenchantable Gear settings underneath." },
                },
            },
            {
                heading = "Fixed",
                items = {
                    { lead = "BatchSell", text = "no longer sells a cosmetic whose appearance you have not collected. Selling one does not collect it — the appearance is simply gone — and the check that was meant to prevent this only ever looked at armor filed under the Cosmetic subclass. Cosmetic weapons are filed as ordinary weapons, so a cosmetic bow or polearm was judged on its item level like any other and vendored. The question is now asked of every item whatever its class, and an item whose appearance state cannot be read is kept rather than risked." },
                    { lead = "BatchSell", text = "compares bows, guns, crossbows and wands against the weapon you are actually holding. They were being weighed against the ranged slot, which the game removed years ago and which is empty on every character — so they never lost the comparison and were never sold, however far behind they had fallen. Expect outgrown ranged weapons to start selling." },
                    { lead = "BatchSell", text = "no longer keeps a soulbound crafting reagent because an alt has the profession that wants it. A bound copy can never reach that alt, so the account-wide answer was the wrong one to ask; it now asks about the character actually holding it. Expect some bound reagents to start selling — they were being kept for a character who could never receive them." },
                    { lead = "Openables", text = "moves to the next item even when using one fails. The button only advanced when the item was actually consumed, so a use the game refused — out of range, wrong zone, on cooldown — left you clicking the same item. It now moves on regardless, and the item is not dropped: it goes to the back and comes round again." },
                    { lead = "Openables", text = "no longer offers profession tools you use out in the world, like the Elusive Creature Lure or a skinning bait on a twelve hour cooldown. They arrive looking exactly like something to open — a plain \"Use:\" line and nothing else — and the only thing separating them is a profession requirement you meet. They used to sit above every genuine learnable in the button's order; now they are not offered at all." },
                    { lead = "BatchSell", text = "no longer keeps gear nobody can ever disenchant. With Keep Disenchantable Gear on, a piece was spared whenever the game would accept it for a disenchant — but a piece you have worn is bound to you, and if you are not an enchanter there is no one it can reach. Those pieces stayed in your bags for good, and on a levelling character that is most of what you outgrow. BatchSell now asks who could actually receive the item: you, if you have the profession; an alt, if it is Warbound; or a buyer, if you have not bound it yet. Expect levelling gear you outgrew to start selling again — it was never doing anything for you." },
                    { lead = "BatchSell", text = "now recognises Warbound gear. It was reading the wrong bind type — the one the game uses for quest items — so gear bound to your warband was never seen as account-bound and could be sold whatever you had set. What spares it is the Spare Bind on Account Gear dropdown, which offers All, Current Expansion and None and ships on Current Expansion: at that setting this expansion's Warbound gear is kept and a past expansion's is not, and All keeps every piece. Enchanters lost the same gear from Keep Disenchantable Gear for the same reason." },
                    { lead = "BatchSell", text = "no longer sells gear that beats what you are wearing, when what you are wearing is last expansion's. Quality counted for a fixed number of item levels whatever its age, so a levelling character in last expansion's epic had this expansion's upgrades vendored for being a tier below it. A piece from a finished expansion now sets its bar on item level alone — no margin, no quality discount. Gear scaled by Timewalking is exempt, since its item level is already current." },
                    { lead = "BatchSell", text = "never sells anything above epic quality. Legendary, artifact and heirloom items were judged like any other gear, so an outgrown legendary was vendored for being behind on item level — and the game reports a sale price for these and then refuses the sale, so one that reached the list quietly used up a slot in the batch and sold nothing. The game will not complete the sale whatever BatchSell does, so there is no setting and no list that makes one happen." },
                    { lead = "BatchSell", text = "no longer sells cloaks, shirts or tabards as gear your class cannot equip. Every class wears all three, but the game files them under cloth, so on anything but a cloth wearer they were being judged as off-class gear and vendored." },
                    { lead = "BatchSell", text = "no longer treats one-handed weapons as gear a hunter wants. No hunter specialization uses one — Beast Mastery and Marksmanship are ranged, Survival is two-handed — so a one-hander picked up while levelling is no longer weighed against what you have equipped. It is not vendored on the spot either: it still faces the bind and disenchant questions, and is kept if it is Warbound, Bind on Equip or worth disenchanting." },
                    { lead = "Openables:", text = "the button updates as soon as you pick something up. It could previously sit on the wrong item, or show nothing at all, until an unrelated bag change happened to refresh it — the item's tooltip had not finished loading when the button first looked at it, and nothing told it when it had." },
                    { lead = "Openables", text = "no longer offers profession knowledge items you cannot study yet. A requirement like \"Requires Dragon Isles Mining (25)\" was treated as met by knowing the profession at all, so an item that needs rank 25 showed up at rank 1." },
                    { lead = "Openables", text = "stops hiding profession knowledge items you can study. The button sizes an item up along one of two paths, and only one of them was reading the item's profession requirement — so on the other path a knowledge item you were entitled to use looked like an ordinary firecracker and was dropped from the button entirely, while a profession-gated lure lost the requirement that would have turned it away and was offered in its place. Both paths now read the same evidence." },
                    { lead = "Openables", text = "now counts housing decor, dyes and room customizations as learnables, so they are offered ahead of items you merely use rather than last." },
                    { lead = "Openables", text = "holds back Focused Life Essence until you carry the five it needs to combine, and no longer offers Superior Loyal Spirit, which does nothing away from its Queen's Conservatory node." },
                    { lead = "RepRank:", text = "the Show factions with no progress toggle now shows its state after you click it. It changed the list correctly but kept the appearance it was built with, so it read as unchanged." },
                    { lead = "Openables:", text = "blacklisted items show their names again. A row in the blacklist window read Unknown item (194829) and stayed that way for the rest of the session — the window asked the game for the name, but nothing was listening for the answer when it came back. Rows only ever looked right for items still sitting in your bags, which is rarely what is on a blacklist." },
                },
            },
        },
    },
    {
        version = "v12.1.0.6",
        date = "2026-08-23",
        sections = {
            {
                heading = "Added",
                items = {
                    { lead = "RepRank:", text = "every faction now carries a progress bar showing how far the leading character is through their current step, so you can see who is close to the next rank rather than only which rank they have reached. The bar is coloured by what kind of progress it is — the game's own standing colours for ordinary reputations, green for friendships, the accent colour for renown, and purple for paragon — and hovering it gives you the exact figures. A faction in paragon shows its paragon progress rather than a permanently full bar. A faction with nothing left to earn shows a full bar and no figures, and one the game has not sent numbers for shows an empty bar rather than a made-up total. The window is wider to make room for the column." },
                },
            },
            {
                heading = "Changed",
                items = {
                    { lead = "RepRank:", text = "character names are shown in class colours — in the window's Best column, in the tooltip listing who has a paragon reward waiting, and in the paragon alerts printed to chat. A character is coloured from the next time you log in on it; until then it looks exactly as it does today." },
                },
            },
        },
    },
    {
        version = "v12.1.0.5",
        date = "2026-08-23",
        sections = {
            {
                heading = "Added",
                items = {
                    { lead = "RepRank", text = ", a new module: it records each character's reputations as you play them and shows who is furthest along with every faction, warband-wide reputations listed apart from the ones that differ per character. It also tells you when any character has a paragon reward waiting — in chat and as a pop-up when one becomes claimable, and again at each login while it is still unclaimed." },
                    { text = "BitForge windows are painted in EllesmereUI's theme when you have it installed, following your accent colour and style settings. Nothing to configure; EllesmereUI's own per-addon skinning toggle controls it. The BatchSell merchant window is the first to use it." },
                },
            },
            {
                heading = "Changed",
                items = {
                    { lead = "BatchSell", text = "now asks three questions about a piece of gear, in order: is it good for me, is it good for one of my alts, is it worth disenchanting? Only gear that fails all three is sold. Previously the comparison against your equipped item had the last word, so a piece it rejected was vendored before the heirloom and disenchanting rules were consulted at all. Off-class gear goes through the same three questions now — a weapon your class cannot use but that binds to the account is kept for the character who can." },
                    { lead = "BatchSell:", text = "the three \"apply margin to higher / equal / lower quality\" checkboxes are replaced by one margin that covers every case. It is now what a quality tier is worth in item levels: at the default of 10, gear a tier below what you have equipped has to beat it by 10 to be kept, and a tier above survives 10 under it. At your own quality a piece has to beat the slot outright. Set it to 0 to ignore quality altogether. The slider runs 0 to 30 in steps of 2 and reads as a plain count of item levels rather than the negative number it used to be. The old checkboxes could contradict each other, so an uncommon could outlive the rare sitting next to it at the same item level; gear is judged consistently now, and more item level or more quality can only ever help a piece survive. The trade-off is that a large quality drop is no longer excused by a small item level gain — a 139 uncommon no longer survives an equipped 134 epic, because two tiers down has to beat it by 20 at the default margin. It is still offered to the heirloom and disenchanting rules before anything sells it. Your existing margin is reset to the new default." },
                    { lead = "BatchSell", text = "has a new \"Emphasize Quality\" option, off by default. It counts a quality tier for twice the margin and lets a piece of your own quality sit that margin below the slot — so quality above what you wear gets cheaper to keep, and quality below it dearer to excuse." },
                    { lead = "BatchSell", text = "no longer sells gear for a slot you have nothing equipped in. There is nothing for it to be worse than, so it is kept — levelling gear for an empty slot is not junk." },
                    { lead = "BatchSell:", text = "with \"Sell Equipment\" turned off, gear tooltips now say what the piece is actually worth — \"good enough against what you have equipped\", \"kept for the character who can use it\", \"worth disenchanting\" — instead of the same \"this kind of item is set to be kept\" on everything. Gear that would have been vendored still names the setting as what saved it. Nothing is sold that was not sold before." },
                    { lead = "Openables", text = "now surfaces profession knowledge items — the ones that read \"Study to increase your <Profession> Knowledge\" — for the professions your character actually has. They are ordinary Miscellaneous items with a plain Use: line, indistinguishable by class from the junk the button deliberately ignores, so they were being skipped. What tells them apart is that they are gated on a trade skill, which nothing you would want ignored ever is." },
                    { lead = "Openables", text = "shows what you can learn from first — recipes, toys, appearances, profession knowledge — then tokens, then caches and lockboxes, then quest items, and last of all anything that is merely usable. The order used to run the other way. A recipe is permanent and easy to forget you are carrying, while a cache keeps until you open it and a quest item is already held on the button by its own gate. An item whose tooltip only says it does something — with nothing to learn from it — now sits below all of them; it used to share the top place with recipes, and could take the button from a cache, a token or a quest item." },
                    { lead = "BatchSell", text = "learns which items can really be disenchanted, instead of trusting only its built-in list. Whenever you put Disenchant on the cursor, the game marks every item in your bags as disenchantable or not; BatchSell reads those marks and remembers them warband-wide. An item the built-in list had wrong stops being judged on it, in either direction — gear that turns out not to be disenchantable is no longer kept for that reason, and gear that turns out to be is no longer sold for the lack of it. Nothing to switch on, no extra clicks, and it only ever reads what the game has already said. Non-enchanters are unaffected." },
                    { lead = "BatchSell:", text = "the sell window now matches the merchant window's width, and its three tabs sit below it rather than above." },
                    { lead = "BatchSell:", text = "\"Your class cannot equip this\" now reads \"Not equippable or not recommended for your class\" — the rule also covers armor your class can technically wear but is not meant to." },
                    { lead = "TaskTome:", text = "the buttons along the top of the tracker window explain themselves. Hovering the gear or the padlock now describes what a click will do, and both light up under the pointer like the two beside them — the gear is how you open the configuration window from the tracker, and there was nothing to suggest it. Opening it from the Settings panel still works." },
                    { lead = "TaskTome:", text = "character names in the tracker are shown in class colours, so a roster of alts is readable at a glance. A character is coloured from the next time you log in on it; until then it looks exactly as it does today." },
                },
            },
            {
                heading = "Fixed",
                items = {
                    { lead = "Openables:", text = "Aqir Relic Fragment is held back until you are carrying six of them. Its tooltip offers a use at any stack size, but the effect combines six, so a click below that did nothing." },
                    { lead = "Openables:", text = "the click instructions on the button's tooltip no longer go missing on the first hover after a login or reload. The tooltip rebuilds itself once the item's data finishes loading, and the instructions were being dropped in that rebuild — which is why moving the mouse away and back brought them back." },
                    { lead = "BatchSell:", text = "gear your class cannot wear is no longer described as outclassed by what you have equipped. A hunter's tooltip on a one-handed mace said the mace was worse than the weapon in hand, when the real reason was simply that a hunter cannot hold one. It still sells; the tooltip now says why." },
                    { lead = "BatchSell:", text = "turning \"Sell Junk\" off now leaves poor quality items alone completely. It only ever stopped BatchSell from using the vendor's own Sell All Junk button — the greys were still judged by the usual rules and sold anyway, which defeated the point of handing them to another addon." },
                    { lead = "BatchSell:", text = "the sell list is no longer empty when you reopen a vendor. Closing and immediately reopening showed nothing until you pressed Refresh, on every visit after the first had cleared your junk." },
                    { lead = "TaskTome:", text = "the tracker window can be moved. Unlocking it with the padlock did nothing at all — the window never took mouse input, so the drag it was listening for could never begin. Locking it still pins it in place." },
                    { lead = "TaskTome:", text = "the tracker window has a close button. Until now the only way to put it away was the minimap icon." },
                },
            },
        },
    },
    {
        version = "v12.1.0.4",
        date = "2026-08-22",
        sections = {
            {
                heading = "Added",
                items = {
                    { lead = "BatchSell", text = "now keeps crafting reagents that a profession on one of your characters actually uses, instead of judging them on expansion age alone. On by default — turn off \"Keep Reagents Your Professions Use\" for the old behaviour." },
                    { lead = "UPS", text = "now deposits only the reagents your professions can craft with. Turn off \"Only deposit reagents you can use\" to send everything to the Warband Bank for the auction house, as before." },
                },
            },
            {
                heading = "Changed",
                items = {
                    { text = "Your characters' professions are remembered by BitForge itself now rather than by UPS, so BatchSell can use them too. Nothing to do — whatever UPS already recorded is carried over." },
                },
            },
            {
                heading = "Fixed",
                items = {
                    { lead = "BatchSell:", text = "the list of items that cannot be disenchanted was badly incomplete — about 2,000 entries where the real figure is over 15,000. Shirts, tabards, rings, trinkets, cloaks and every cosmetic item were missing entirely, so BatchSell treated them as disenchantable and offered them for sale on that basis. All of them are now recognised." },
                },
            },
        },
    },
    {
        version = "v12.1.0.3",
        date = "2026-08-21",
        sections = {
            {
                heading = "Added",
                items = {
                    { lead = "BatchSell", sep = "—", text = "your blacklist and whitelist are now readable from the merchant window. The sell list gained tabs, so you can see everything on each list, remove entries one at a time, and watch the sell list re-decide immediately. Previously the lists were write-only: you could add an item but the only way back was resetting a whole list." },
                    { lead = "BatchSell", sep = "—", text = "drag an item from your bags onto the sell list to sell it on this visit only. It is forgotten when you close the merchant, and it never overrides your blacklist, an equipment set, a locked item, or something no vendor will buy — if you drag one of those, it tells you why in chat. Dragging in something you had temporarily excluded simply changes your mind back." },
                    { lead = "BatchSell", sep = "—", text = "item tooltips at a vendor now tell you whether the item will be sold or kept, and which rule decided it." },
                },
            },
            {
                heading = "Changed",
                items = {
                    { lead = "BatchSell", sep = "—", text = "a substantial rework of what gets sold. Nothing is vendored now unless a rule specifically selects it, where previously anything no rule protected was fair game. Gear is judged against what you are actually wearing in that slot rather than against typed-in numbers: the item level margin and the quality thresholds are gone, replaced by a margin you can apply separately to gear of higher, equal, or lower quality than your own. Crafting materials and consumables each gained their own setting — keep everything, keep the current expansion, keep from an expansion you choose, or sell it all. Please review your settings before your next vendor trip. The old \"Keep Equippable\" option, the quality threshold, and the past-expansion toggles no longer exist, and your saved values for them are cleared automatically." },
                    { lead = "BatchSell", sep = "—", text = "the settings panel is grouped into collapsible sections — General, Equipment, Crafting Materials, Consumables & Other, and Lists — instead of one long list." },
                },
            },
            {
                heading = "Fixed",
                items = {
                    { lead = "BitForge", sep = "—", text = "the minimap button reacts to being pressed again. Holding it down was meant to zoom the icon in slightly as an acknowledgement, but the effect never appeared and raised an error every time instead." },
                },
            },
        },
    },
}
