name: Generate Wiki Docs

on:
  push:
    branches:
      - main  # Change to "master" if that's your primary branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install emmylua_doc_cli
        run: cargo install emmylua_doc_cli

      - name: Generate Markdown
        run: |
          emmylua_doc_cli ./BitForge -o ./temp_wiki -f markdown --site-name "BitForge API"

      - name: Deploy to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: ./temp_wiki
          token: ${{ secrets.GITHUB_TOKEN }}